name: py_entitymatching_dev
channels:
  - conda-forge
  - uwmagellan
  - defaults
dependencies:
    - setuptools
    - py_stringsimjoin == 0.1.0
    - cloudpickle
    - pyparsing
    - scikit-learn >= 0.18
    - pyqt
    - py_stringmatching
    - pandas-profiling
    - requests
#    - xgboost
