package:
  name: py_entitymatching
  version: "0.1.0"

source:
    git_url: ../


requirements:
  build:
    - python
    - setuptools
    - py_stringsimjoin
    - cloudpickle
    - pyparsing
    - scikit-learn
    - pyqt == 4.11.4

  run:
    - python
    - py_stringsimjoin
    - cloudpickle
    - pyparsing
    - scikit-learn
    - pyqt == 4.11.4

test:
  # Python imports
  imports:
    - py_entitymatching

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://sites.google.com/site/anhaidgroup/projects/py_entitymatching
  license: BSD License
  summary: 'Python library for string matching.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
